services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\Cart\:
    resource: '../Classes/*'
    exclude: '../Classes/Widgets/*'

  querybuilder.tx_cart_domain_model_order_item:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_cart_domain_model_order_item'
