services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Extcode\Cart\:
    resource: '../Classes/*'
    exclude: '../Classes/Widgets/*'

  Extcode\Cart\Domain\Finisher\Order\ClearCartFinisher:
    tags:
      - name: event.listener
        identifier: 'cart-clear-cart-finisher'
        event: Extcode\Cart\Event\ProcessOrderCreateEvent

  Extcode\Cart\Domain\Finisher\Order\EmailFinisher:
    tags:
      - name: event.listener
        identifier: 'cart-email-finisher'
        event: Extcode\Cart\Event\ProcessOrderCreateEvent
        after: 'cart-order-finisher'
        before: 'cart-clear-cart-finisher'

  Extcode\Cart\Domain\Finisher\Order\OrderFinisher:
    tags:
      - name: event.listener
        identifier: 'cart-order-finisher'
        event: Extcode\Cart\Event\ProcessOrderCreateEvent
        before: 'cart-order-number-finisher'

  Extcode\Cart\Domain\Finisher\Order\OrderNumberFinisher:
    arguments:
      $persistenceManager: '@TYPO3\CMS\Extbase\Persistence\Generic\PersistenceManager'
    tags:
      - name: event.listener
        identifier: 'cart-order-number-finisher'
        event: Extcode\Cart\Event\ProcessOrderCreateEvent
        after: 'cart-order-finisher'

  Extcode\Cart\Service\TaxClassService:
    public: true

  querybuilder.tx_cart_domain_model_order_item:
    class: 'TYPO3\CMS\Core\Database\Query\QueryBuilder'
    factory:
      - '@TYPO3\CMS\Core\Database\ConnectionPool'
      - 'getQueryBuilderForTable'
    arguments:
      - 'tx_cart_domain_model_order_item'
